name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["Build Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download Docker Image
        uses: actions/download-artifact@v2
        with:
          name: docker-image
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username mishikabatra --password-stdin

      - name: Push Docker Image
        run: docker push mishikabatra/pipeline:latest

      - name: Run Docker Container
        run: docker run -d -p 80:80 mishikabatra/pipeline:latest
