# deploy.yml
name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull pipeline:latest

      - name: Stop previous nginx container (if exists)
        run: docker stop nginx-container || true

      - name: Remove previous nginx container (if exists)
        run: docker rm nginx-container || true

      - name: Run new nginx container
        run: docker run -d -p 80:80 --name nginx-container pipeline:latest
